In [167]:
import pandas as pd

In [168]:
# Se cargan los datos en un dataframe y mostramos la información del dataset
data = pd.read_csv('dataset.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3163 entries, 0 to 3162
Data columns (total 25 columns):
Unnamed: 0                   3163 non-null int64
on_thyroxine                 3163 non-null object
query_on_thyroxine           3163 non-null object
on_antithyroid_medication    3163 non-null object
thyroid_surgery              3163 non-null object
query_hypothyroid            3163 non-null object
query_hyperthyroid           3163 non-null object
pregnant                     3163 non-null object
sick                         3163 non-null object
tumor                        3163 non-null object
lithium                      3163 non-null object
goitre                       3163 non-null object
TSH_measured                 3163 non-null object
T3_measured                  3163 non-null object
TT4_measured                 3163 non-null object
T4U_measured                 3163 non-null object
FTI_measured                 3163 non-null object
TBG_measured                 3163 non-null object
age                          3163 non-null int64
sex                          3163 non-null object
TSH                          3163 non-null float64
T3                           3163 non-null float64
TT4                          3163 non-null float64
T4U                          3163 non-null float64
FTI                          3163 non-null float64
dtypes: float64(5), int64(2), object(18)
memory usage: 617.9+ KB

In [169]:
# Se muestran los nombres de los atributos
data.columns

Index(['Unnamed: 0', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'thyroid_surgery', 'query_hypothyroid',
       'query_hyperthyroid', 'pregnant', 'sick', 'tumor', 'lithium', 'goitre',
       'TSH_measured', 'T3_measured', 'TT4_measured', 'T4U_measured',
       'FTI_measured', 'TBG_measured', 'age', 'sex', 'TSH', 'T3', 'TT4', 'T4U',
       'FTI'],
      dtype='object')

In [170]:
# Estadísticas básicas de las variables numéricas del dataset
data.describe()

,Unnamed: 0,age,TSH,T3,TT4,T4U,FTI
count,3163.000000,3163.000000,3163.000000,3163.000000,3163.000000,3163.000000,3163.000000
mean,1582.000000,51.367689,5.675081,1.990168,108.993645,0.983127,114.786247
std,913.223777,19.218782,22.915041,1.035535,45.041256,0.234183,58.937419
min,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000
25%,791.500000,35.000000,0.000000,1.400000,83.000000,0.850000,90.500000
50%,1582.000000,54.000000,0.700000,1.900000,104.000000,0.960000,107.000000
75%,2372.500000,67.000000,2.200000,2.400000,128.000000,1.070000,128.000000
max,3163.000000,98.000000,530.000000,10.200000,450.000000,2.210000,881.000000

In [171]:
# Se muestran las primeras 5 muestras del dataset
data.head()

,Unnamed: 0,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,sick,tumor,...,T4U_measured,FTI_measured,TBG_measured,age,sex,TSH,T3,TT4,T4U,FTI
0,1,f,f,f,f,f,f,f,f,f,...,y,y,n,72,M,0.80,1.0,83.0,0.95,87.0
1,2,f,f,f,f,f,f,f,f,f,...,y,y,n,45,F,1.90,1.0,82.0,0.73,112.0
2,3,f,f,f,f,f,f,f,t,f,...,y,y,n,64,F,0.09,1.0,101.0,0.82,123.0
3,4,f,f,f,f,f,f,f,f,f,...,y,y,n,56,M,0.00,0.8,76.0,0.77,99.0
4,5,t,f,f,f,t,f,f,f,f,...,y,y,n,78,F,2.60,0.3,87.0,0.95,91.0

In [172]:
# La primer columna es una serie de índices la cual no nos resulta de utilidad
# Se procede a eliminarla
data.drop(data.columns[0], 1, inplace=True)
data.head()

,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,sick,tumor,lithium,...,T4U_measured,FTI_measured,TBG_measured,age,sex,TSH,T3,TT4,T4U,FTI
0,f,f,f,f,f,f,f,f,f,f,...,y,y,n,72,M,0.80,1.0,83.0,0.95,87.0
1,f,f,f,f,f,f,f,f,f,f,...,y,y,n,45,F,1.90,1.0,82.0,0.73,112.0
2,f,f,f,f,f,f,f,t,f,f,...,y,y,n,64,F,0.09,1.0,101.0,0.82,123.0
3,f,f,f,f,f,f,f,f,f,f,...,y,y,n,56,M,0.00,0.8,76.0,0.77,99.0
4,t,f,f,f,t,f,f,f,f,f,...,y,y,n,78,F,2.60,0.3,87.0,0.95,91.0

In [173]:
# La variable categórica TGB_measured da información acerca de si existe una medición en la 
# variable TGB, la cual fue eliminada anteriormente en la fase de imputación, por tanto 
# procedemos a eliminar dicha columna también
data.drop('TBG_measured', 1, inplace=True)
data.head()

,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,sick,tumor,lithium,...,TT4_measured,T4U_measured,FTI_measured,age,sex,TSH,T3,TT4,T4U,FTI
0,f,f,f,f,f,f,f,f,f,f,...,y,y,y,72,M,0.80,1.0,83.0,0.95,87.0
1,f,f,f,f,f,f,f,f,f,f,...,y,y,y,45,F,1.90,1.0,82.0,0.73,112.0
2,f,f,f,f,f,f,f,t,f,f,...,y,y,y,64,F,0.09,1.0,101.0,0.82,123.0
3,f,f,f,f,f,f,f,f,f,f,...,y,y,y,56,M,0.00,0.8,76.0,0.77,99.0
4,t,f,f,f,t,f,f,f,f,f,...,y,y,y,78,F,2.60,0.3,87.0,0.95,91.0

In [174]:
# Basados en la información obtenida del conjunto de datos original, el cual se encuentra en
# https://archive.ics.uci.edu/ml/machine-learning-databases/thyroid-disease/sick-euthyroid.data
# la primer columna de dicho dataset indica la clase correspondiente a la muestra
# Fácilmente se puede observar que la cantidad de muestras de la clase sick-euthyroid es de 293
# mientras que la cantidad de muestras de clase negative es de 2870.
# En el dataset actual no se cuenta con dicha columna, por tanto se procede a agregarla al conjunto

In [175]:
# Se crea la lista de clases
sick_euthyroid = ['sick-euthyroid' for i in range(293)]
negative = ['negative' for i in range(2870)]

classes = sick_euthyroid + negative
classes

['sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'sick-euthyroid',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 ...]

In [176]:
# Se agrega al dataset
data['classes'] = classes
data.head()

,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,sick,tumor,lithium,...,T4U_measured,FTI_measured,age,sex,TSH,T3,TT4,T4U,FTI,classes
0,f,f,f,f,f,f,f,f,f,f,...,y,y,72,M,0.80,1.0,83.0,0.95,87.0,sick-euthyroid
1,f,f,f,f,f,f,f,f,f,f,...,y,y,45,F,1.90,1.0,82.0,0.73,112.0,sick-euthyroid
2,f,f,f,f,f,f,f,t,f,f,...,y,y,64,F,0.09,1.0,101.0,0.82,123.0,sick-euthyroid
3,f,f,f,f,f,f,f,f,f,f,...,y,y,56,M,0.00,0.8,76.0,0.77,99.0,sick-euthyroid
4,t,f,f,f,t,f,f,f,f,f,...,y,y,78,F,2.60,0.3,87.0,0.95,91.0,sick-euthyroid

In [177]:
# Se hace un conteo de muestras por clases
data.classes.value_counts()

negative          2870
sick-euthyroid     293
Name: classes, dtype: int64

In [178]:
# Se convierte variable sex a valores de 0 y 1
data['sex'] = data['sex'].map({'F': 0, 'M': 1})

In [179]:
# Se convierten variables con valires f y t a valores de 0 y 1

data['sick'] = data['sick'].map({'f': 0, 't': 1})
data['tumor'] = data['tumor'].map({'f': 0, 't': 1})
data['goitre'] = data['goitre'].map({'f': 0, 't': 1})
data['lithium'] = data['lithium'].map({'f': 0, 't': 1})
data['pregnant'] = data['pregnant'].map({'f': 0, 't': 1})
data['on_thyroxine'] = data['on_thyroxine'].map({'f': 0, 't': 1})
data['thyroid_surgery'] = data['thyroid_surgery'].map({'f': 0, 't': 1})
data['query_hypothyroid'] = data['query_hypothyroid'].map({'f': 0, 't': 1})
data['query_hyperthyroid'] = data['query_hyperthyroid'].map({'f': 0, 't': 1})
data['query_on_thyroxine'] = data['query_on_thyroxine'].map({'f': 0, 't': 1})
data['on_antithyroid_medication'] = data['on_antithyroid_medication'].map({'f': 0, 't': 1})

In [180]:
# Se convierte variables con valores n e y a valores de 0 y 1
data['T3_measured'] = data['T3_measured'].map({'n': 0, 'y': 1})
data['TSH_measured'] = data['TSH_measured'].map({'n': 0, 'y': 1})
data['TT4_measured'] = data['TT4_measured'].map({'n': 0, 'y': 1})
data['T4U_measured'] = data['T4U_measured'].map({'n': 0, 'y': 1})
data['FTI_measured'] = data['FTI_measured'].map({'n': 0, 'y': 1})

In [181]:
# Se convierte variable classes a valores de 0 y 1
data['classes'] = data['classes'].map({'negative': 0, 'sick-euthyroid': 1})

In [182]:
data.head()

,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,sick,tumor,lithium,...,T4U_measured,FTI_measured,age,sex,TSH,T3,TT4,T4U,FTI,classes
0,0,0,0,0,0,0,0,0,0,0,...,1,1,72,1,0.80,1.0,83.0,0.95,87.0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,1,45,0,1.90,1.0,82.0,0.73,112.0,1
2,0,0,0,0,0,0,0,1,0,0,...,1,1,64,0,0.09,1.0,101.0,0.82,123.0,1
3,0,0,0,0,0,0,0,0,0,0,...,1,1,56,1,0.00,0.8,76.0,0.77,99.0,1
4,1,0,0,0,1,0,0,0,0,0,...,1,1,78,0,2.60,0.3,87.0,0.95,91.0,1

In [183]:
data.shape

(3163, 24)

In [185]:
data.to_csv('full_dataset.csv', index=False)